/* 
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChangeUserRoleDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChangeUserRoleDTOTests
    {
        // TODO uncomment below to declare an instance variable for ChangeUserRoleDTO
        //private ChangeUserRoleDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChangeUserRoleDTO
            //instance = new ChangeUserRoleDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChangeUserRoleDTO
        /// </summary>
        [Test]
        public void ChangeUserRoleDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChangeUserRoleDTO
            //Assert.IsInstanceOfType<ChangeUserRoleDTO> (instance, "variable 'instance' is a ChangeUserRoleDTO");
        }


        /// <summary>
        /// Test the property 'ActiveRole'
        /// </summary>
        [Test]
        public void ActiveRoleTest()
        {
            // TODO unit test for the property 'ActiveRole'
        }

    }

}
