/* 
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateProjectDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateProjectDTOTests
    {
        // TODO uncomment below to declare an instance variable for CreateProjectDTO
        //private CreateProjectDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateProjectDTO
            //instance = new CreateProjectDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateProjectDTO
        /// </summary>
        [Test]
        public void CreateProjectDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateProjectDTO
            //Assert.IsInstanceOfType<CreateProjectDTO> (instance, "variable 'instance' is a CreateProjectDTO");
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Skills'
        /// </summary>
        [Test]
        public void SkillsTest()
        {
            // TODO unit test for the property 'Skills'
        }
        /// <summary>
        /// Test the property 'MinBudget'
        /// </summary>
        [Test]
        public void MinBudgetTest()
        {
            // TODO unit test for the property 'MinBudget'
        }
        /// <summary>
        /// Test the property 'MaxBudget'
        /// </summary>
        [Test]
        public void MaxBudgetTest()
        {
            // TODO unit test for the property 'MaxBudget'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'DeadlineDate'
        /// </summary>
        [Test]
        public void DeadlineDateTest()
        {
            // TODO unit test for the property 'DeadlineDate'
        }

    }

}
