/* 
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OfferInfoDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OfferInfoDTOTests
    {
        // TODO uncomment below to declare an instance variable for OfferInfoDTO
        //private OfferInfoDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OfferInfoDTO
            //instance = new OfferInfoDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OfferInfoDTO
        /// </summary>
        [Test]
        public void OfferInfoDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OfferInfoDTO
            //Assert.IsInstanceOfType<OfferInfoDTO> (instance, "variable 'instance' is a OfferInfoDTO");
        }


        /// <summary>
        /// Test the property 'FreelancerId'
        /// </summary>
        [Test]
        public void FreelancerIdTest()
        {
            // TODO unit test for the property 'FreelancerId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Budget'
        /// </summary>
        [Test]
        public void BudgetTest()
        {
            // TODO unit test for the property 'Budget'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
