/* 
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProjectInfoDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProjectInfoDTOTests
    {
        // TODO uncomment below to declare an instance variable for ProjectInfoDTO
        //private ProjectInfoDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProjectInfoDTO
            //instance = new ProjectInfoDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectInfoDTO
        /// </summary>
        [Test]
        public void ProjectInfoDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProjectInfoDTO
            //Assert.IsInstanceOfType<ProjectInfoDTO> (instance, "variable 'instance' is a ProjectInfoDTO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Skills'
        /// </summary>
        [Test]
        public void SkillsTest()
        {
            // TODO unit test for the property 'Skills'
        }
        /// <summary>
        /// Test the property 'MinBudget'
        /// </summary>
        [Test]
        public void MinBudgetTest()
        {
            // TODO unit test for the property 'MinBudget'
        }
        /// <summary>
        /// Test the property 'MaxBudget'
        /// </summary>
        [Test]
        public void MaxBudgetTest()
        {
            // TODO unit test for the property 'MaxBudget'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'DeadlineDate'
        /// </summary>
        [Test]
        public void DeadlineDateTest()
        {
            // TODO unit test for the property 'DeadlineDate'
        }
        /// <summary>
        /// Test the property 'RealEndDate'
        /// </summary>
        [Test]
        public void RealEndDateTest()
        {
            // TODO unit test for the property 'RealEndDate'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SelectedFreelancerId'
        /// </summary>
        [Test]
        public void SelectedFreelancerIdTest()
        {
            // TODO unit test for the property 'SelectedFreelancerId'
        }
        /// <summary>
        /// Test the property 'Offers'
        /// </summary>
        [Test]
        public void OffersTest()
        {
            // TODO unit test for the property 'Offers'
        }

    }

}
