/* 
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubmitOfferDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmitOfferDTOTests
    {
        // TODO uncomment below to declare an instance variable for SubmitOfferDTO
        //private SubmitOfferDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmitOfferDTO
            //instance = new SubmitOfferDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmitOfferDTO
        /// </summary>
        [Test]
        public void SubmitOfferDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmitOfferDTO
            //Assert.IsInstanceOfType<SubmitOfferDTO> (instance, "variable 'instance' is a SubmitOfferDTO");
        }


        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Budget'
        /// </summary>
        [Test]
        public void BudgetTest()
        {
            // TODO unit test for the property 'Budget'
        }

    }

}
