/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProjectSeekerApi);
  }
}(this, function(expect, ProjectSeekerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ChangeUserRoleDTO', function() {
      beforeEach(function() {
        instance = new ProjectSeekerApi.ChangeUserRoleDTO();
      });

      it('should create an instance of ChangeUserRoleDTO', function() {
        // TODO: update the code to test ChangeUserRoleDTO
        expect(instance).to.be.a(ProjectSeekerApi.ChangeUserRoleDTO);
      });

      it('should have the property activeRole (base name: "activeRole")', function() {
        // TODO: update the code to test the property activeRole
        expect(instance).to.have.property('activeRole');
        // expect(instance.activeRole).to.be(expectedValueLiteral);
      });

    });
  });

}));
