/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProjectSeekerApi);
  }
}(this, function(expect, ProjectSeekerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateUserDTO', function() {
      beforeEach(function() {
        instance = new ProjectSeekerApi.CreateUserDTO();
      });

      it('should create an instance of CreateUserDTO', function() {
        // TODO: update the code to test CreateUserDTO
        expect(instance).to.be.a(ProjectSeekerApi.CreateUserDTO);
      });

      it('should have the property firebaseId (base name: "firebaseId")', function() {
        // TODO: update the code to test the property firebaseId
        expect(instance).to.have.property('firebaseId');
        // expect(instance.firebaseId).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property email (base name: "email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property phone (base name: "phone")', function() {
        // TODO: update the code to test the property phone
        expect(instance).to.have.property('phone');
        // expect(instance.phone).to.be(expectedValueLiteral);
      });

      it('should have the property activeRole (base name: "activeRole")', function() {
        // TODO: update the code to test the property activeRole
        expect(instance).to.have.property('activeRole');
        // expect(instance.activeRole).to.be(expectedValueLiteral);
      });

    });
  });

}));
