/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProjectSeekerApi);
  }
}(this, function(expect, ProjectSeekerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ErrorDTO', function() {
      beforeEach(function() {
        instance = new ProjectSeekerApi.ErrorDTO();
      });

      it('should create an instance of ErrorDTO', function() {
        // TODO: update the code to test ErrorDTO
        expect(instance).to.be.a(ProjectSeekerApi.ErrorDTO);
      });

      it('should have the property timestamp (base name: "timestamp")', function() {
        // TODO: update the code to test the property timestamp
        expect(instance).to.have.property('timestamp');
        // expect(instance.timestamp).to.be(expectedValueLiteral);
      });

      it('should have the property httpErrorCode (base name: "httpErrorCode")', function() {
        // TODO: update the code to test the property httpErrorCode
        expect(instance).to.have.property('httpErrorCode');
        // expect(instance.httpErrorCode).to.be(expectedValueLiteral);
      });

      it('should have the property firebaseError (base name: "firebaseError")', function() {
        // TODO: update the code to test the property firebaseError
        expect(instance).to.have.property('firebaseError');
        // expect(instance.firebaseError).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

    });
  });

}));
