/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProjectSeekerApi);
  }
}(this, function(expect, ProjectSeekerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('OfferInfoDTO', function() {
      beforeEach(function() {
        instance = new ProjectSeekerApi.OfferInfoDTO();
      });

      it('should create an instance of OfferInfoDTO', function() {
        // TODO: update the code to test OfferInfoDTO
        expect(instance).to.be.a(ProjectSeekerApi.OfferInfoDTO);
      });

      it('should have the property freelancerId (base name: "freelancerId")', function() {
        // TODO: update the code to test the property freelancerId
        expect(instance).to.have.property('freelancerId');
        // expect(instance.freelancerId).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property budget (base name: "budget")', function() {
        // TODO: update the code to test the property budget
        expect(instance).to.have.property('budget');
        // expect(instance.budget).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

    });
  });

}));
