<?php
/**
 * ProjectsEndpointsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProjectsEndpointsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectsEndpointsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for assignFreelancer
     *
     * Assign freelancer.
     *
     */
    public function testAssignFreelancer()
    {
    }

    /**
     * Test case for createProject
     *
     * Create project.
     *
     */
    public function testCreateProject()
    {
    }

    /**
     * Test case for finishProject
     *
     * Finish project.
     *
     */
    public function testFinishProject()
    {
    }

    /**
     * Test case for getInProgressProjectsByClientId
     *
     * Get the projects I have created that are in progress.
     *
     */
    public function testGetInProgressProjectsByClientId()
    {
    }

    /**
     * Test case for getOpenProjects
     *
     * Get all open projects.
     *
     */
    public function testGetOpenProjects()
    {
    }

    /**
     * Test case for getOpenProjectsByClient
     *
     * Get the projects I have created that are open.
     *
     */
    public function testGetOpenProjectsByClient()
    {
    }

    /**
     * Test case for getOpenProjectsBySkills
     *
     * Get open projects by skills.
     *
     */
    public function testGetOpenProjectsBySkills()
    {
    }

    /**
     * Test case for getPrjectInfo
     *
     * Get project info.
     *
     */
    public function testGetPrjectInfo()
    {
    }

    /**
     * Test case for getProjectsByAssignedFreelancer
     *
     * Get projects assigned to me.
     *
     */
    public function testGetProjectsByAssignedFreelancer()
    {
    }

    /**
     * Test case for getProjectsByClient
     *
     * Get the projects I have created.
     *
     */
    public function testGetProjectsByClient()
    {
    }

    /**
     * Test case for getProjectsByOfferFreelancer
     *
     * Get projects where I have made an offer.
     *
     */
    public function testGetProjectsByOfferFreelancer()
    {
    }

    /**
     * Test case for submitOffer
     *
     * Submit offer.
     *
     */
    public function testSubmitOffer()
    {
    }
}
