<?php
/**
 * UsersEndpointsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersEndpointsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersEndpointsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addOrUpdateDeviceFCMToken
     *
     * Add device for notifications.
     *
     */
    public function testAddOrUpdateDeviceFCMToken()
    {
    }

    /**
     * Test case for changeRole
     *
     * Change user role.
     *
     */
    public function testChangeRole()
    {
    }

    /**
     * Test case for createUser
     *
     * Create user.
     *
     */
    public function testCreateUser()
    {
    }

    /**
     * Test case for deleteUser
     *
     * Delete user.
     *
     */
    public function testDeleteUser()
    {
    }

    /**
     * Test case for getMyProfile
     *
     * Get my profile.
     *
     */
    public function testGetMyProfile()
    {
    }

    /**
     * Test case for getProfile
     *
     * Get profile.
     *
     */
    public function testGetProfile()
    {
    }

    /**
     * Test case for modifyClientProfile
     *
     * Modify client profile.
     *
     */
    public function testModifyClientProfile()
    {
    }

    /**
     * Test case for modifyFreelancerProfile
     *
     * Modify freelancer profile.
     *
     */
    public function testModifyFreelancerProfile()
    {
    }
}
