/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProjectSeekerApi);
  }
}(this, function(expect, ProjectSeekerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProjectSeekerApi.SessionEndpointsApi();
  });

  describe('(package)', function() {
    describe('SessionEndpointsApi', function() {
      describe('sessionLogin', function() {
        it('should call sessionLogin successfully', function(done) {
          // TODO: uncomment sessionLogin call
          /*

          instance.sessionLogin(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('sessionLogout', function() {
        it('should call sessionLogout successfully', function(done) {
          // TODO: uncomment sessionLogout call
          /*

          instance.sessionLogout(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('sessionLogoutEverywhere', function() {
        it('should call sessionLogoutEverywhere successfully', function(done) {
          // TODO: uncomment sessionLogoutEverywhere call
          /*

          instance.sessionLogoutEverywhere(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
