/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProjectSeekerApi);
  }
}(this, function(expect, ProjectSeekerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProjectSeekerApi.UsersEndpointsApi();
  });

  describe('(package)', function() {
    describe('UsersEndpointsApi', function() {
      describe('addOrUpdateDeviceFCMToken', function() {
        it('should call addOrUpdateDeviceFCMToken successfully', function(done) {
          // TODO: uncomment, update parameter values for addOrUpdateDeviceFCMToken call
          /*

          instance.addOrUpdateDeviceFCMToken(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('changeRole', function() {
        it('should call changeRole successfully', function(done) {
          // TODO: uncomment, update parameter values for changeRole call and complete the assertions
          /*

          instance.changeRole(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProjectSeekerApi.ProfileDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createUser', function() {
        it('should call createUser successfully', function(done) {
          // TODO: uncomment, update parameter values for createUser call and complete the assertions
          /*

          instance.createUser(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProjectSeekerApi.ProfileDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteUser', function() {
        it('should call deleteUser successfully', function(done) {
          // TODO: uncomment deleteUser call
          /*

          instance.deleteUser(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMyProfile', function() {
        it('should call getMyProfile successfully', function(done) {
          // TODO: uncomment getMyProfile call and complete the assertions
          /*

          instance.getMyProfile(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProjectSeekerApi.ProfileDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getProfile', function() {
        it('should call getProfile successfully', function(done) {
          // TODO: uncomment, update parameter values for getProfile call and complete the assertions
          /*

          instance.getProfile(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProjectSeekerApi.ProfileDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('modifyClientProfile', function() {
        it('should call modifyClientProfile successfully', function(done) {
          // TODO: uncomment, update parameter values for modifyClientProfile call and complete the assertions
          /*

          instance.modifyClientProfile(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProjectSeekerApi.ProfileDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('modifyFreelancerProfile', function() {
        it('should call modifyFreelancerProfile successfully', function(done) {
          // TODO: uncomment, update parameter values for modifyFreelancerProfile call and complete the assertions
          /*

          instance.modifyFreelancerProfile(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProjectSeekerApi.ProfileDTO);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
