# coding: utf-8

"""
    Project Seeker API

    Project Seeker API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jorgetargz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddDeviceDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'firebase_id': 'str',
        'device_model': 'str',
        'device_token': 'str'
    }

    attribute_map = {
        'firebase_id': 'firebaseId',
        'device_model': 'deviceModel',
        'device_token': 'deviceToken'
    }

    def __init__(self, firebase_id=None, device_model=None, device_token=None):  # noqa: E501
        """AddDeviceDTO - a model defined in Swagger"""  # noqa: E501
        self._firebase_id = None
        self._device_model = None
        self._device_token = None
        self.discriminator = None
        if firebase_id is not None:
            self.firebase_id = firebase_id
        if device_model is not None:
            self.device_model = device_model
        if device_token is not None:
            self.device_token = device_token

    @property
    def firebase_id(self):
        """Gets the firebase_id of this AddDeviceDTO.  # noqa: E501


        :return: The firebase_id of this AddDeviceDTO.  # noqa: E501
        :rtype: str
        """
        return self._firebase_id

    @firebase_id.setter
    def firebase_id(self, firebase_id):
        """Sets the firebase_id of this AddDeviceDTO.


        :param firebase_id: The firebase_id of this AddDeviceDTO.  # noqa: E501
        :type: str
        """

        self._firebase_id = firebase_id

    @property
    def device_model(self):
        """Gets the device_model of this AddDeviceDTO.  # noqa: E501


        :return: The device_model of this AddDeviceDTO.  # noqa: E501
        :rtype: str
        """
        return self._device_model

    @device_model.setter
    def device_model(self, device_model):
        """Sets the device_model of this AddDeviceDTO.


        :param device_model: The device_model of this AddDeviceDTO.  # noqa: E501
        :type: str
        """

        self._device_model = device_model

    @property
    def device_token(self):
        """Gets the device_token of this AddDeviceDTO.  # noqa: E501


        :return: The device_token of this AddDeviceDTO.  # noqa: E501
        :rtype: str
        """
        return self._device_token

    @device_token.setter
    def device_token(self, device_token):
        """Sets the device_token of this AddDeviceDTO.


        :param device_token: The device_token of this AddDeviceDTO.  # noqa: E501
        :type: str
        """

        self._device_token = device_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddDeviceDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddDeviceDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
