# coding: utf-8

"""
    Project Seeker API

    Project Seeker API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jorgetargz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.super_admin_endpoints_api import SuperAdminEndpointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSuperAdminEndpointsApi(unittest.TestCase):
    """SuperAdminEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = SuperAdminEndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_disable_user(self):
        """Test case for disable_user

        Disable user  # noqa: E501
        """
        pass

    def test_enable_user(self):
        """Test case for enable_user

        Enable user  # noqa: E501
        """
        pass

    def test_get_user_by_email(self):
        """Test case for get_user_by_email

        Get user by email  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
