# coding: utf-8

"""
    Project Seeker API

    Project Seeker API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jorgetargz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.assign_project_dto import AssignProjectDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestAssignProjectDTO(unittest.TestCase):
    """AssignProjectDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssignProjectDTO(self):
        """Test AssignProjectDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.assign_project_dto.AssignProjectDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
