# coding: utf-8

"""
    Project Seeker API

    Project Seeker API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jorgetargz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.add_device_dto import AddDeviceDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestAddDeviceDTO(unittest.TestCase):
    """AddDeviceDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddDeviceDTO(self):
        """Test AddDeviceDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.add_device_dto.AddDeviceDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
