# coding: utf-8

"""
    Project Seeker API

    Project Seeker API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jorgetargz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_dto import ErrorDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorDTO(unittest.TestCase):
    """ErrorDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorDTO(self):
        """Test ErrorDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_dto.ErrorDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
