# coding: utf-8

"""
    Project Seeker API

    Project Seeker API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jorgetargz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_endpoints_api import UsersEndpointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersEndpointsApi(unittest.TestCase):
    """UsersEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = UsersEndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_or_update_device_fcm_token(self):
        """Test case for add_or_update_device_fcm_token

        Add device for notifications  # noqa: E501
        """
        pass

    def test_change_role(self):
        """Test case for change_role

        Change user role  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create user  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete user  # noqa: E501
        """
        pass

    def test_get_my_profile(self):
        """Test case for get_my_profile

        Get my profile  # noqa: E501
        """
        pass

    def test_get_profile(self):
        """Test case for get_profile

        Get profile  # noqa: E501
        """
        pass

    def test_modify_client_profile(self):
        """Test case for modify_client_profile

        Modify client profile  # noqa: E501
        """
        pass

    def test_modify_freelancer_profile(self):
        """Test case for modify_freelancer_profile

        Modify freelancer profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
