# coding: utf-8

"""
    Project Seeker API

    Project Seeker API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jorgetargz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.change_user_role_dto import ChangeUserRoleDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestChangeUserRoleDTO(unittest.TestCase):
    """ChangeUserRoleDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeUserRoleDTO(self):
        """Test ChangeUserRoleDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.change_user_role_dto.ChangeUserRoleDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
