# coding: utf-8

"""
    Project Seeker API

    Project Seeker API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: jorgetargz@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projects_endpoints_api import ProjectsEndpointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectsEndpointsApi(unittest.TestCase):
    """ProjectsEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsEndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_freelancer(self):
        """Test case for assign_freelancer

        Assign freelancer  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create project  # noqa: E501
        """
        pass

    def test_finish_project(self):
        """Test case for finish_project

        Finish project  # noqa: E501
        """
        pass

    def test_get_in_progress_projects_by_client_id(self):
        """Test case for get_in_progress_projects_by_client_id

        Get the projects I have created that are in progress  # noqa: E501
        """
        pass

    def test_get_open_projects(self):
        """Test case for get_open_projects

        Get all open projects  # noqa: E501
        """
        pass

    def test_get_open_projects_by_client(self):
        """Test case for get_open_projects_by_client

        Get the projects I have created that are open  # noqa: E501
        """
        pass

    def test_get_open_projects_by_skills(self):
        """Test case for get_open_projects_by_skills

        Get open projects by skills  # noqa: E501
        """
        pass

    def test_get_prject_info(self):
        """Test case for get_prject_info

        Get project info  # noqa: E501
        """
        pass

    def test_get_projects_by_assigned_freelancer(self):
        """Test case for get_projects_by_assigned_freelancer

        Get projects assigned to me  # noqa: E501
        """
        pass

    def test_get_projects_by_client(self):
        """Test case for get_projects_by_client

        Get the projects I have created  # noqa: E501
        """
        pass

    def test_get_projects_by_offer_freelancer(self):
        """Test case for get_projects_by_offer_freelancer

        Get projects where I have made an offer  # noqa: E501
        """
        pass

    def test_submit_offer(self):
        """Test case for submit_offer

        Submit offer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
