# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AddDeviceDTO(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, firebase_id: str=None, device_model: str=None, device_token: str=None):  # noqa: E501
        """AddDeviceDTO - a model defined in Swagger

        :param firebase_id: The firebase_id of this AddDeviceDTO.  # noqa: E501
        :type firebase_id: str
        :param device_model: The device_model of this AddDeviceDTO.  # noqa: E501
        :type device_model: str
        :param device_token: The device_token of this AddDeviceDTO.  # noqa: E501
        :type device_token: str
        """
        self.swagger_types = {
            'firebase_id': str,
            'device_model': str,
            'device_token': str
        }

        self.attribute_map = {
            'firebase_id': 'firebaseId',
            'device_model': 'deviceModel',
            'device_token': 'deviceToken'
        }
        self._firebase_id = firebase_id
        self._device_model = device_model
        self._device_token = device_token

    @classmethod
    def from_dict(cls, dikt) -> 'AddDeviceDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddDeviceDTO of this AddDeviceDTO.  # noqa: E501
        :rtype: AddDeviceDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def firebase_id(self) -> str:
        """Gets the firebase_id of this AddDeviceDTO.


        :return: The firebase_id of this AddDeviceDTO.
        :rtype: str
        """
        return self._firebase_id

    @firebase_id.setter
    def firebase_id(self, firebase_id: str):
        """Sets the firebase_id of this AddDeviceDTO.


        :param firebase_id: The firebase_id of this AddDeviceDTO.
        :type firebase_id: str
        """

        self._firebase_id = firebase_id

    @property
    def device_model(self) -> str:
        """Gets the device_model of this AddDeviceDTO.


        :return: The device_model of this AddDeviceDTO.
        :rtype: str
        """
        return self._device_model

    @device_model.setter
    def device_model(self, device_model: str):
        """Sets the device_model of this AddDeviceDTO.


        :param device_model: The device_model of this AddDeviceDTO.
        :type device_model: str
        """

        self._device_model = device_model

    @property
    def device_token(self) -> str:
        """Gets the device_token of this AddDeviceDTO.


        :return: The device_token of this AddDeviceDTO.
        :rtype: str
        """
        return self._device_token

    @device_token.setter
    def device_token(self, device_token: str):
        """Sets the device_token of this AddDeviceDTO.


        :param device_token: The device_token of this AddDeviceDTO.
        :type device_token: str
        """

        self._device_token = device_token
