# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AssignProjectDTO(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, project_id: str=None, freelancer_id: str=None):  # noqa: E501
        """AssignProjectDTO - a model defined in Swagger

        :param project_id: The project_id of this AssignProjectDTO.  # noqa: E501
        :type project_id: str
        :param freelancer_id: The freelancer_id of this AssignProjectDTO.  # noqa: E501
        :type freelancer_id: str
        """
        self.swagger_types = {
            'project_id': str,
            'freelancer_id': str
        }

        self.attribute_map = {
            'project_id': 'projectId',
            'freelancer_id': 'freelancerId'
        }
        self._project_id = project_id
        self._freelancer_id = freelancer_id

    @classmethod
    def from_dict(cls, dikt) -> 'AssignProjectDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssignProjectDTO of this AssignProjectDTO.  # noqa: E501
        :rtype: AssignProjectDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def project_id(self) -> str:
        """Gets the project_id of this AssignProjectDTO.


        :return: The project_id of this AssignProjectDTO.
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: str):
        """Sets the project_id of this AssignProjectDTO.


        :param project_id: The project_id of this AssignProjectDTO.
        :type project_id: str
        """

        self._project_id = project_id

    @property
    def freelancer_id(self) -> str:
        """Gets the freelancer_id of this AssignProjectDTO.


        :return: The freelancer_id of this AssignProjectDTO.
        :rtype: str
        """
        return self._freelancer_id

    @freelancer_id.setter
    def freelancer_id(self, freelancer_id: str):
        """Sets the freelancer_id of this AssignProjectDTO.


        :param freelancer_id: The freelancer_id of this AssignProjectDTO.
        :type freelancer_id: str
        """

        self._freelancer_id = freelancer_id
