# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateProjectDTO(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None, skills: List[str]=None, min_budget: float=None, max_budget: float=None, start_date: date=None, deadline_date: date=None):  # noqa: E501
        """CreateProjectDTO - a model defined in Swagger

        :param title: The title of this CreateProjectDTO.  # noqa: E501
        :type title: str
        :param description: The description of this CreateProjectDTO.  # noqa: E501
        :type description: str
        :param skills: The skills of this CreateProjectDTO.  # noqa: E501
        :type skills: List[str]
        :param min_budget: The min_budget of this CreateProjectDTO.  # noqa: E501
        :type min_budget: float
        :param max_budget: The max_budget of this CreateProjectDTO.  # noqa: E501
        :type max_budget: float
        :param start_date: The start_date of this CreateProjectDTO.  # noqa: E501
        :type start_date: date
        :param deadline_date: The deadline_date of this CreateProjectDTO.  # noqa: E501
        :type deadline_date: date
        """
        self.swagger_types = {
            'title': str,
            'description': str,
            'skills': List[str],
            'min_budget': float,
            'max_budget': float,
            'start_date': date,
            'deadline_date': date
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            'skills': 'skills',
            'min_budget': 'minBudget',
            'max_budget': 'maxBudget',
            'start_date': 'startDate',
            'deadline_date': 'deadlineDate'
        }
        self._title = title
        self._description = description
        self._skills = skills
        self._min_budget = min_budget
        self._max_budget = max_budget
        self._start_date = start_date
        self._deadline_date = deadline_date

    @classmethod
    def from_dict(cls, dikt) -> 'CreateProjectDTO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateProjectDTO of this CreateProjectDTO.  # noqa: E501
        :rtype: CreateProjectDTO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this CreateProjectDTO.


        :return: The title of this CreateProjectDTO.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this CreateProjectDTO.


        :param title: The title of this CreateProjectDTO.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this CreateProjectDTO.


        :return: The description of this CreateProjectDTO.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this CreateProjectDTO.


        :param description: The description of this CreateProjectDTO.
        :type description: str
        """

        self._description = description

    @property
    def skills(self) -> List[str]:
        """Gets the skills of this CreateProjectDTO.


        :return: The skills of this CreateProjectDTO.
        :rtype: List[str]
        """
        return self._skills

    @skills.setter
    def skills(self, skills: List[str]):
        """Sets the skills of this CreateProjectDTO.


        :param skills: The skills of this CreateProjectDTO.
        :type skills: List[str]
        """

        self._skills = skills

    @property
    def min_budget(self) -> float:
        """Gets the min_budget of this CreateProjectDTO.


        :return: The min_budget of this CreateProjectDTO.
        :rtype: float
        """
        return self._min_budget

    @min_budget.setter
    def min_budget(self, min_budget: float):
        """Sets the min_budget of this CreateProjectDTO.


        :param min_budget: The min_budget of this CreateProjectDTO.
        :type min_budget: float
        """

        self._min_budget = min_budget

    @property
    def max_budget(self) -> float:
        """Gets the max_budget of this CreateProjectDTO.


        :return: The max_budget of this CreateProjectDTO.
        :rtype: float
        """
        return self._max_budget

    @max_budget.setter
    def max_budget(self, max_budget: float):
        """Sets the max_budget of this CreateProjectDTO.


        :param max_budget: The max_budget of this CreateProjectDTO.
        :type max_budget: float
        """

        self._max_budget = max_budget

    @property
    def start_date(self) -> date:
        """Gets the start_date of this CreateProjectDTO.


        :return: The start_date of this CreateProjectDTO.
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: date):
        """Sets the start_date of this CreateProjectDTO.


        :param start_date: The start_date of this CreateProjectDTO.
        :type start_date: date
        """

        self._start_date = start_date

    @property
    def deadline_date(self) -> date:
        """Gets the deadline_date of this CreateProjectDTO.


        :return: The deadline_date of this CreateProjectDTO.
        :rtype: date
        """
        return self._deadline_date

    @deadline_date.setter
    def deadline_date(self, deadline_date: date):
        """Sets the deadline_date of this CreateProjectDTO.


        :param deadline_date: The deadline_date of this CreateProjectDTO.
        :type deadline_date: date
        """

        self._deadline_date = deadline_date
