/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AddDeviceDTO} from './model/AddDeviceDTO';
import {AssignProjectDTO} from './model/AssignProjectDTO';
import {ChangeUserRoleDTO} from './model/ChangeUserRoleDTO';
import {CreateProjectDTO} from './model/CreateProjectDTO';
import {CreateUserDTO} from './model/CreateUserDTO';
import {ErrorDTO} from './model/ErrorDTO';
import {ModifyClientProfileDTO} from './model/ModifyClientProfileDTO';
import {ModifyFreelancerProfileDTO} from './model/ModifyFreelancerProfileDTO';
import {OfferInfoDTO} from './model/OfferInfoDTO';
import {ProfileDTO} from './model/ProfileDTO';
import {ProjectInfoDTO} from './model/ProjectInfoDTO';
import {SubmitOfferDTO} from './model/SubmitOfferDTO';
import {ProjectsEndpointsApi} from './api/ProjectsEndpointsApi';
import {SessionEndpointsApi} from './api/SessionEndpointsApi';
import {SuperAdminEndpointsApi} from './api/SuperAdminEndpointsApi';
import {UsersEndpointsApi} from './api/UsersEndpointsApi';

/**
* Project_Seeker_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ProjectSeekerApi = require('index'); // See note below*.
* var xxxSvc = new ProjectSeekerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ProjectSeekerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ProjectSeekerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ProjectSeekerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddDeviceDTO model constructor.
     * @property {module:model/AddDeviceDTO}
     */
    AddDeviceDTO,

    /**
     * The AssignProjectDTO model constructor.
     * @property {module:model/AssignProjectDTO}
     */
    AssignProjectDTO,

    /**
     * The ChangeUserRoleDTO model constructor.
     * @property {module:model/ChangeUserRoleDTO}
     */
    ChangeUserRoleDTO,

    /**
     * The CreateProjectDTO model constructor.
     * @property {module:model/CreateProjectDTO}
     */
    CreateProjectDTO,

    /**
     * The CreateUserDTO model constructor.
     * @property {module:model/CreateUserDTO}
     */
    CreateUserDTO,

    /**
     * The ErrorDTO model constructor.
     * @property {module:model/ErrorDTO}
     */
    ErrorDTO,

    /**
     * The ModifyClientProfileDTO model constructor.
     * @property {module:model/ModifyClientProfileDTO}
     */
    ModifyClientProfileDTO,

    /**
     * The ModifyFreelancerProfileDTO model constructor.
     * @property {module:model/ModifyFreelancerProfileDTO}
     */
    ModifyFreelancerProfileDTO,

    /**
     * The OfferInfoDTO model constructor.
     * @property {module:model/OfferInfoDTO}
     */
    OfferInfoDTO,

    /**
     * The ProfileDTO model constructor.
     * @property {module:model/ProfileDTO}
     */
    ProfileDTO,

    /**
     * The ProjectInfoDTO model constructor.
     * @property {module:model/ProjectInfoDTO}
     */
    ProjectInfoDTO,

    /**
     * The SubmitOfferDTO model constructor.
     * @property {module:model/SubmitOfferDTO}
     */
    SubmitOfferDTO,

    /**
    * The ProjectsEndpointsApi service constructor.
    * @property {module:api/ProjectsEndpointsApi}
    */
    ProjectsEndpointsApi,

    /**
    * The SessionEndpointsApi service constructor.
    * @property {module:api/SessionEndpointsApi}
    */
    SessionEndpointsApi,

    /**
    * The SuperAdminEndpointsApi service constructor.
    * @property {module:api/SuperAdminEndpointsApi}
    */
    SuperAdminEndpointsApi,

    /**
    * The UsersEndpointsApi service constructor.
    * @property {module:api/UsersEndpointsApi}
    */
    UsersEndpointsApi
};
