/* 
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProjectsEndpointsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProjectsEndpointsApiTests
    {
        private ProjectsEndpointsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProjectsEndpointsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectsEndpointsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProjectsEndpointsApi
            //Assert.IsInstanceOfType(typeof(ProjectsEndpointsApi), instance, "instance is a ProjectsEndpointsApi");
        }

        /// <summary>
        /// Test AssignFreelancer
        /// </summary>
        [Test]
        public void AssignFreelancerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AssignProjectDTO body = null;
            //var response = instance.AssignFreelancer(body);
            //Assert.IsInstanceOf<ProjectInfoDTO> (response, "response is ProjectInfoDTO");
        }
        /// <summary>
        /// Test CreateProject
        /// </summary>
        [Test]
        public void CreateProjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateProjectDTO body = null;
            //var response = instance.CreateProject(body);
            //Assert.IsInstanceOf<ProjectInfoDTO> (response, "response is ProjectInfoDTO");
        }
        /// <summary>
        /// Test FinishProject
        /// </summary>
        [Test]
        public void FinishProjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.FinishProject(id);
            //Assert.IsInstanceOf<ProjectInfoDTO> (response, "response is ProjectInfoDTO");
        }
        /// <summary>
        /// Test GetInProgressProjectsByClientId
        /// </summary>
        [Test]
        public void GetInProgressProjectsByClientIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetInProgressProjectsByClientId();
            //Assert.IsInstanceOf<List<ProjectInfoDTO>> (response, "response is List<ProjectInfoDTO>");
        }
        /// <summary>
        /// Test GetOpenProjects
        /// </summary>
        [Test]
        public void GetOpenProjectsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetOpenProjects();
            //Assert.IsInstanceOf<List<ProjectInfoDTO>> (response, "response is List<ProjectInfoDTO>");
        }
        /// <summary>
        /// Test GetOpenProjectsByClient
        /// </summary>
        [Test]
        public void GetOpenProjectsByClientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetOpenProjectsByClient();
            //Assert.IsInstanceOf<List<ProjectInfoDTO>> (response, "response is List<ProjectInfoDTO>");
        }
        /// <summary>
        /// Test GetOpenProjectsBySkills
        /// </summary>
        [Test]
        public void GetOpenProjectsBySkillsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> body = null;
            //var response = instance.GetOpenProjectsBySkills(body);
            //Assert.IsInstanceOf<List<ProjectInfoDTO>> (response, "response is List<ProjectInfoDTO>");
        }
        /// <summary>
        /// Test GetPrjectInfo
        /// </summary>
        [Test]
        public void GetPrjectInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetPrjectInfo(id);
            //Assert.IsInstanceOf<ProjectInfoDTO> (response, "response is ProjectInfoDTO");
        }
        /// <summary>
        /// Test GetProjectsByAssignedFreelancer
        /// </summary>
        [Test]
        public void GetProjectsByAssignedFreelancerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetProjectsByAssignedFreelancer();
            //Assert.IsInstanceOf<List<ProjectInfoDTO>> (response, "response is List<ProjectInfoDTO>");
        }
        /// <summary>
        /// Test GetProjectsByClient
        /// </summary>
        [Test]
        public void GetProjectsByClientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetProjectsByClient();
            //Assert.IsInstanceOf<List<ProjectInfoDTO>> (response, "response is List<ProjectInfoDTO>");
        }
        /// <summary>
        /// Test GetProjectsByOfferFreelancer
        /// </summary>
        [Test]
        public void GetProjectsByOfferFreelancerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetProjectsByOfferFreelancer();
            //Assert.IsInstanceOf<List<ProjectInfoDTO>> (response, "response is List<ProjectInfoDTO>");
        }
        /// <summary>
        /// Test SubmitOffer
        /// </summary>
        [Test]
        public void SubmitOfferTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SubmitOfferDTO body = null;
            //var response = instance.SubmitOffer(body);
            //Assert.IsInstanceOf<ProjectInfoDTO> (response, "response is ProjectInfoDTO");
        }
    }

}
