/* 
 * Project Seeker API
 *
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SuperAdminEndpointsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SuperAdminEndpointsApiTests
    {
        private SuperAdminEndpointsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SuperAdminEndpointsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SuperAdminEndpointsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SuperAdminEndpointsApi
            //Assert.IsInstanceOfType(typeof(SuperAdminEndpointsApi), instance, "instance is a SuperAdminEndpointsApi");
        }

        /// <summary>
        /// Test DisableUser
        /// </summary>
        [Test]
        public void DisableUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string email = null;
            //instance.DisableUser(email);
            
        }
        /// <summary>
        /// Test EnableUser
        /// </summary>
        [Test]
        public void EnableUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string email = null;
            //instance.EnableUser(email);
            
        }
        /// <summary>
        /// Test GetUserByEmail
        /// </summary>
        [Test]
        public void GetUserByEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string email = null;
            //var response = instance.GetUserByEmail(email);
            //Assert.IsInstanceOf<ProfileDTO> (response, "response is ProfileDTO");
        }
    }

}
