/**
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param firebaseId 
 * @param deviceModel 
 * @param deviceToken 
 */
data class AddDeviceDTO (

    val firebaseId: kotlin.String? = null,
    val deviceModel: kotlin.String? = null,
    val deviceToken: kotlin.String? = null
) {
}