/**
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param timestamp 
 * @param httpErrorCode 
 * @param firebaseError 
 * @param message 
 * @param description 
 */
data class ErrorDTO (

    val timestamp: java.time.LocalDateTime? = null,
    val httpErrorCode: kotlin.Int? = null,
    val firebaseError: kotlin.String? = null,
    val message: kotlin.String? = null,
    val description: kotlin.String? = null
) {
}