/**
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param firebaseId 
 * @param name 
 * @param email 
 * @param phone 
 * @param activeRole 
 * @param title 
 * @param description 
 * @param availability 
 * @param rating 
 * @param skills 
 */
data class ProfileDTO (

    val id: kotlin.String? = null,
    val firebaseId: kotlin.String? = null,
    val name: kotlin.String? = null,
    val email: kotlin.String? = null,
    val phone: kotlin.String? = null,
    val activeRole: kotlin.String? = null,
    val title: kotlin.String? = null,
    val description: kotlin.String? = null,
    val availability: kotlin.String? = null,
    val rating: kotlin.Double? = null,
    val skills: kotlin.Array<kotlin.String>? = null
) {
}