/**
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.OfferInfoDTO

/**
 * 
 * @param id 
 * @param clientId 
 * @param title 
 * @param description 
 * @param skills 
 * @param minBudget 
 * @param maxBudget 
 * @param startDate 
 * @param deadlineDate 
 * @param realEndDate 
 * @param status 
 * @param selectedFreelancerId 
 * @param offers 
 */
data class ProjectInfoDTO (

    val id: kotlin.String? = null,
    val clientId: kotlin.String? = null,
    val title: kotlin.String? = null,
    val description: kotlin.String? = null,
    val skills: kotlin.Array<kotlin.String>? = null,
    val minBudget: kotlin.Double? = null,
    val maxBudget: kotlin.Double? = null,
    val startDate: java.time.LocalDate? = null,
    val deadlineDate: java.time.LocalDate? = null,
    val realEndDate: java.time.LocalDate? = null,
    val status: kotlin.String? = null,
    val selectedFreelancerId: kotlin.String? = null,
    val offers: kotlin.Array<OfferInfoDTO>? = null
) {
}