/**
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param projectId 
 * @param description 
 * @param budget 
 */
data class SubmitOfferDTO (

    val projectId: kotlin.String? = null,
    val description: kotlin.String? = null,
    val budget: kotlin.Double? = null
) {
}