/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateUserDTO model module.
 * @module model/CreateUserDTO
 * @version 1.0
 */
export class CreateUserDTO {
  /**
   * Constructs a new <code>CreateUserDTO</code>.
   * @alias module:model/CreateUserDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateUserDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateUserDTO} obj Optional instance to populate.
   * @return {module:model/CreateUserDTO} The populated <code>CreateUserDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateUserDTO();
      if (data.hasOwnProperty('firebaseId'))
        obj.firebaseId = ApiClient.convertToType(data['firebaseId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('activeRole'))
        obj.activeRole = ApiClient.convertToType(data['activeRole'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} firebaseId
 */
CreateUserDTO.prototype.firebaseId = undefined;

/**
 * @member {String} name
 */
CreateUserDTO.prototype.name = undefined;

/**
 * @member {String} email
 */
CreateUserDTO.prototype.email = undefined;

/**
 * @member {String} phone
 */
CreateUserDTO.prototype.phone = undefined;

/**
 * @member {String} activeRole
 */
CreateUserDTO.prototype.activeRole = undefined;

