/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ModifyFreelancerProfileDTO model module.
 * @module model/ModifyFreelancerProfileDTO
 * @version 1.0
 */
export class ModifyFreelancerProfileDTO {
  /**
   * Constructs a new <code>ModifyFreelancerProfileDTO</code>.
   * @alias module:model/ModifyFreelancerProfileDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModifyFreelancerProfileDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModifyFreelancerProfileDTO} obj Optional instance to populate.
   * @return {module:model/ModifyFreelancerProfileDTO} The populated <code>ModifyFreelancerProfileDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModifyFreelancerProfileDTO();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('skills'))
        obj.skills = ApiClient.convertToType(data['skills'], ['String']);
      if (data.hasOwnProperty('availability'))
        obj.availability = ApiClient.convertToType(data['availability'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
ModifyFreelancerProfileDTO.prototype.title = undefined;

/**
 * @member {String} description
 */
ModifyFreelancerProfileDTO.prototype.description = undefined;

/**
 * @member {Array.<String>} skills
 */
ModifyFreelancerProfileDTO.prototype.skills = undefined;

/**
 * @member {String} availability
 */
ModifyFreelancerProfileDTO.prototype.availability = undefined;

