/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ModifyClientProfileDTO model module.
 * @module model/ModifyClientProfileDTO
 * @version 1.0
 */
export class ModifyClientProfileDTO {
  /**
   * Constructs a new <code>ModifyClientProfileDTO</code>.
   * @alias module:model/ModifyClientProfileDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModifyClientProfileDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModifyClientProfileDTO} obj Optional instance to populate.
   * @return {module:model/ModifyClientProfileDTO} The populated <code>ModifyClientProfileDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModifyClientProfileDTO();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
ModifyClientProfileDTO.prototype.title = undefined;

/**
 * @member {String} description
 */
ModifyClientProfileDTO.prototype.description = undefined;

