/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ErrorDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SessionEndpointsApi
 */
@Ignore
public class SessionEndpointsApiTest {

    private final SessionEndpointsApi api = new SessionEndpointsApi();

    /**
     * Login user with firebase token and create session cookie
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sessionLoginTest() throws Exception {
        api.sessionLogin();

        // TODO: test validations
    }
    /**
     * Logout user and delete session cookie
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sessionLogoutTest() throws Exception {
        api.sessionLogout();

        // TODO: test validations
    }
    /**
     * Logout user everywhere and delete session cookie
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sessionLogoutEverywhereTest() throws Exception {
        api.sessionLogoutEverywhere();

        // TODO: test validations
    }
}
