/*
 * Project Seeker API
 * Project Seeker API
 *
 * OpenAPI spec version: 1.0
 * Contact: jorgetargz@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AddDeviceDTO;
import io.swagger.client.model.ChangeUserRoleDTO;
import io.swagger.client.model.CreateUserDTO;
import io.swagger.client.model.ErrorDTO;
import io.swagger.client.model.ModifyClientProfileDTO;
import io.swagger.client.model.ModifyFreelancerProfileDTO;
import io.swagger.client.model.ProfileDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UsersEndpointsApi
 */
@Ignore
public class UsersEndpointsApiTest {

    private final UsersEndpointsApi api = new UsersEndpointsApi();

    /**
     * Add device for notifications
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addOrUpdateDeviceFCMTokenTest() throws Exception {
        AddDeviceDTO body = null;
        api.addOrUpdateDeviceFCMToken(body);

        // TODO: test validations
    }
    /**
     * Change user role
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void changeRoleTest() throws Exception {
        ChangeUserRoleDTO body = null;
        ProfileDTO response = api.changeRole(body);

        // TODO: test validations
    }
    /**
     * Create user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws Exception {
        CreateUserDTO body = null;
        ProfileDTO response = api.createUser(body);

        // TODO: test validations
    }
    /**
     * Delete user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws Exception {
        api.deleteUser();

        // TODO: test validations
    }
    /**
     * Get my profile
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMyProfileTest() throws Exception {
        ProfileDTO response = api.getMyProfile();

        // TODO: test validations
    }
    /**
     * Get profile
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getProfileTest() throws Exception {
        String id = null;
        ProfileDTO response = api.getProfile(id);

        // TODO: test validations
    }
    /**
     * Modify client profile
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void modifyClientProfileTest() throws Exception {
        ModifyClientProfileDTO body = null;
        ProfileDTO response = api.modifyClientProfile(body);

        // TODO: test validations
    }
    /**
     * Modify freelancer profile
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void modifyFreelancerProfileTest() throws Exception {
        ModifyFreelancerProfileDTO body = null;
        ProfileDTO response = api.modifyFreelancerProfile(body);

        // TODO: test validations
    }
}
